@host=http://localhost:5283

POST {{host}}/auth/register
Content-Type: application/json

{
  "firstName": "Arthur",
  "lastName": "Leywin",
  "email": "art@quad.moe",
  "password": "vrtradumb"
}
